#include templates.js
#include libs/jquery.contextmenu.js
#include libs/jquery.typing-0.2.0.min.js
#include libs/html.sortable.js
#include libs/ResizeSensor.js
#include grid.js
#include note.js
#include console.js
#include main.js